spring:
  application:
    name: apollo-portal
  profiles:
    active: github,auth

server:
  port: 8070
  
logging:
  file: /opt/logs/apollo/apollo-portal.log

endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 


